version: '3.8'

services:
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSGRES_DB: lee_test
      POSTGRES_USER: derrosi
      POSTGRES_PASSWORD: Test1234
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: derrossilee@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Test1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db


volumes:
  postgres_data:
  pgadmin_data: